# TCL File Generated by Component Editor 20.1
# Wed Jul 22 21:14:22 CEST 2026
# DO NOT MODIFY


# 
# cgp_watchdog "cgp_watchdog" v1.0
# lgog 2026.07.22.21:14:22
# CGP Watchdog with Avalon-MM interface. Version 1.0 supports dynamic reconfiguration via memory map. Fault injection not implemented yet
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module cgp_watchdog
# 
set_module_property DESCRIPTION "CGP Watchdog with Avalon-MM interface. Version 1.0 supports dynamic reconfiguration via memory map. Fault injection not implemented yet"
set_module_property NAME cgp_watchdog
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP lgog_IP
set_module_property AUTHOR lgog
set_module_property DISPLAY_NAME cgp_watchdog
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file consts_pkg.vhd VHDL PATH consts_pkg.vhd
add_fileset_file LUT4Cell.vhd VHDL PATH LUT4Cell.vhd
add_fileset_file core.vhd VHDL PATH core.vhd
add_fileset_file wrapper.vhd VHDL PATH wrapper.vhd TOP_LEVEL_FILE
add_fileset_file UART_detector.vhd VHDL PATH UART_detector.vhd


# 
# parameters
# 
add_parameter TICKS_3HZ INTEGER 16666666
set_parameter_property TICKS_3HZ DEFAULT_VALUE 16666666
set_parameter_property TICKS_3HZ DISPLAY_NAME TICKS_3HZ
set_parameter_property TICKS_3HZ TYPE INTEGER
set_parameter_property TICKS_3HZ UNITS None
set_parameter_property TICKS_3HZ HDL_PARAMETER true
add_parameter DEBOUNCE_CYCLES INTEGER 500000
set_parameter_property DEBOUNCE_CYCLES DEFAULT_VALUE 500000
set_parameter_property DEBOUNCE_CYCLES DISPLAY_NAME DEBOUNCE_CYCLES
set_parameter_property DEBOUNCE_CYCLES TYPE INTEGER
set_parameter_property DEBOUNCE_CYCLES UNITS None
set_parameter_property DEBOUNCE_CYCLES HDL_PARAMETER true
add_parameter MAX_FITNESS INTEGER 24
set_parameter_property MAX_FITNESS DEFAULT_VALUE 24
set_parameter_property MAX_FITNESS DISPLAY_NAME MAX_FITNESS
set_parameter_property MAX_FITNESS TYPE INTEGER
set_parameter_property MAX_FITNESS UNITS None
set_parameter_property MAX_FITNESS HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits SYMBOLS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 1
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avs_address address Input 12
add_interface_port avalon_slave_0 avs_chipselect chipselect Input 1
add_interface_port avalon_slave_0 avs_read read Input 1
add_interface_port avalon_slave_0 avs_waitrequest waitrequest Output 1
add_interface_port avalon_slave_0 avs_readdata readdata Output 32
add_interface_port avalon_slave_0 avs_write write Input 1
add_interface_port avalon_slave_0 avs_writedata writedata Input 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point interrupt_sender_0
# 
add_interface interrupt_sender_0 interrupt end
set_interface_property interrupt_sender_0 associatedAddressablePoint avalon_slave_0
set_interface_property interrupt_sender_0 associatedClock clock
set_interface_property interrupt_sender_0 bridgedReceiverOffset ""
set_interface_property interrupt_sender_0 bridgesToReceiver ""
set_interface_property interrupt_sender_0 ENABLED true
set_interface_property interrupt_sender_0 EXPORT_OF ""
set_interface_property interrupt_sender_0 PORT_NAME_MAP ""
set_interface_property interrupt_sender_0 CMSIS_SVD_VARIABLES ""
set_interface_property interrupt_sender_0 SVD_ADDRESS_GROUP ""

add_interface_port interrupt_sender_0 ins_irq irq Output 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point conduit_end
# 
add_interface conduit_end conduit end
set_interface_property conduit_end associatedClock clock
set_interface_property conduit_end associatedReset ""
set_interface_property conduit_end ENABLED true
set_interface_property conduit_end EXPORT_OF ""
set_interface_property conduit_end PORT_NAME_MAP ""
set_interface_property conduit_end CMSIS_SVD_VARIABLES ""
set_interface_property conduit_end SVD_ADDRESS_GROUP ""

add_interface_port conduit_end analog_x_in analog_x_in Input 2
add_interface_port conduit_end analog_y_out analog_y_out Output 3
add_interface_port conduit_end panic_flag_out panic_flag_out Output 1
add_interface_port conduit_end debug_bus debug_bus Output 24
add_interface_port conduit_end uart_rx_in uart_rx_in Input 1

